### ISSUE TITLE
APIs 文档描述错误

### ISSUE THREAD

**Issue by Hunlongyu** [leeenx/timer#1]
name | type | syntax | detail
---|--- | --- | --- 
pauseInterval | Function | timer.pauseInterval(setIntervalID) | 暂停指定 ID 的 setInterval
resumeInterval | Function | timer.resumeInterval(setIntervalID) | 恢复指定 ID 的 setInterval

**Comment by leeenx** [comment]
@Hunlongyu  好的谢谢指正

**Comment by Hunlongyu** [comment]
哈哈~ 看了大神的代码，又学习到不少东西~
