### ISSUE TITLE
请问这个组件只能暂停一次么？

### ISSUE THREAD

**Issue by shilucus** [leeenx/timer#3]
pause 以后 resume，然后再点 pause就不生效了。
点击 resume多次就会跑的很快。。
```
	var siv1T = 0,
		siv1 = timer.setInterval(function() {
			$('.siv-text').text(siv1T++)
		}, 1000)

	$('.siv-clear').on('click', function() {
		timer.clearInterval(siv1);
	});
	$('.siv-pause').on('click', function() {
		timer.pauseInterval(siv1);
	});
	$('.siv-resume').on('click', function() {
		timer.resumeInterval(siv1);
	});
```

**Comment by leeenx** [comment]
@shilucus ,请你的应用情况是 PC 吗？如果移动端的话建议你使用：https://github.com/leeenx/es6-utils/blob/master/modules/timer.js

当前这个 `timer` ，是临时写的没有做过测试。您说的不能暂停多次的问题确实存在，可以改用 timer.pause & timer.resume 来解决这个问题。因为 resumeIntervalue 的时候产生了一个新的 setIntervalID。`timer.pause & timer.resume` 可以暂停和恢复全部的 setInterval & setTimeout。如果您需要单点控制 setInterval 的话，我后续出个版本修复一下

**Comment by leeenx** [comment]
@shilucus 拉一下最新代码试一下。刚更新了一个修复版本，解决了 pauseIntvale & resumeInterval 的问题

**Comment by shilucus** [comment]
@leeenx 你好，demo 是在pc端完成的。
以上问题已经得到优化，这是个很有用的组件，希望可以继续优化拓展。
非常感谢！

**Comment by leeenx** [comment]
@shilucus 好的。谢谢
